version: '3'
services:
  addon:
    container_name: ui-example
    restart: always
    build: .
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    ports:
      - "8080:8080"
    entrypoint: npm run dev
