version: '3.8'
services:
  addon:
    container_name: pumble-notifications-addon
    image: pumble-notifications-addon
    build:
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      PUBLIC_URL:
      ADDON_KEY: pumblenotifications
      ADDON_NAME: Pumble Notifications
      ADDON_DESCRIPTION: A sample addon that registers Clockify webhooks and then posts a message to the configured Pumble channel whenever the events are triggered.
      LOCAL_PORT: 8080
      MONGO_URI: mongodb://root:123456@mongo:27017/?authSource=admin
      MONGO_DATABASE: pumble-notifications
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456