version: '3.8'
services:
  addon:
    container_name: hello-world-addon
    image: hello-world-addon
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      PUBLIC_URL:
      ADDON_KEY: helloworld
      ADDON_NAME: Hello World
      ADDON_DESCRIPTION: A sample addon that renders a UI component
      LOCAL_PORT: 8080
